# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aipair < Formula
  desc "Multiplayer AI coding sessions"
  homepage "https://github.com/rnaudi/aipair"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rnaudi/aipair/releases/download/v0.1.2/aipair-darwin-amd64.tar.gz"
      sha256 "996f9c935d748232347b584ee862a399889a0faddd921034f7d6c45f128a82b7"

      define_method(:install) do
        bin.install "aipair"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rnaudi/aipair/releases/download/v0.1.2/aipair-darwin-arm64.tar.gz"
      sha256 "c71376f521611d5d78ce091275869a083d4b5a924033d5480d6215f9828c58d9"

      define_method(:install) do
        bin.install "aipair"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnaudi/aipair/releases/download/v0.1.2/aipair-linux-amd64.tar.gz"
      sha256 "c3ce48e602add8e733808e7bdf2f5f2bed538f0ad716771225be0e2033bf12de"
      define_method(:install) do
        bin.install "aipair"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnaudi/aipair/releases/download/v0.1.2/aipair-linux-arm64.tar.gz"
      sha256 "7755142e2458794038ba475b87724c400cb55fc0b13cee64aec7956408dfb89b"
      define_method(:install) do
        bin.install "aipair"
      end
    end
  end

  test do
    system "#{bin}/aipair", "--version"
  end
end
