# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aitrace < Formula
  desc "Zero-config agent tracer"
  homepage "https://github.com/rnaudi/aitrace"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rnaudi/aitrace/releases/download/v0.1.2/aitrace-darwin-amd64.tar.gz"
      sha256 "b7029e5081c466b446cf6228a5402328e5a48a940dc75c0bd524fc73739f6728"

      define_method(:install) do
        bin.install "aitrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rnaudi/aitrace/releases/download/v0.1.2/aitrace-darwin-arm64.tar.gz"
      sha256 "78a990a619df283c6030f8ecbadc2f16860ee9d89b9925423b2c602e8836fe35"

      define_method(:install) do
        bin.install "aitrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnaudi/aitrace/releases/download/v0.1.2/aitrace-linux-amd64.tar.gz"
      sha256 "335596f10763928508c0bc317be38ecdaed72b46844adcf1298a81d47ef04f95"
      define_method(:install) do
        bin.install "aitrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnaudi/aitrace/releases/download/v0.1.2/aitrace-linux-arm64.tar.gz"
      sha256 "d82ffe4d69ccce50138f86ac2cf0b4e14d51966e7734b91dad65776f953771c3"
      define_method(:install) do
        bin.install "aitrace"
      end
    end
  end

  test do
    system "#{bin}/aitrace", "--version"
  end
end
