# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aitrace < Formula
  desc "Zero-config agent tracer"
  homepage "https://github.com/rnaudi/aitrace"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rnaudi/aitrace/releases/download/v0.1.1/aitrace-darwin-amd64.tar.gz"
      sha256 "fa63e8caf0998a8e0039ee1e5069755798682106bb20bf47910f5a9c8bd8d79a"

      define_method(:install) do
        bin.install "aitrace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rnaudi/aitrace/releases/download/v0.1.1/aitrace-darwin-arm64.tar.gz"
      sha256 "cbc28d8d3b8481b85f2b26f09fee87c71297da7a6076e6d4d104298a4026ab95"

      define_method(:install) do
        bin.install "aitrace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnaudi/aitrace/releases/download/v0.1.1/aitrace-linux-amd64.tar.gz"
      sha256 "a92907a122c9f0ac23689c7b58cb594b66535f4a235cb49fd7969730b4d0a8c3"
      define_method(:install) do
        bin.install "aitrace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rnaudi/aitrace/releases/download/v0.1.1/aitrace-linux-arm64.tar.gz"
      sha256 "34aace794bfbe72d53bc9e55a5b4ef22dab3d8a9eba27dae2a08bd54cd9ad19d"
      define_method(:install) do
        bin.install "aitrace"
      end
    end
  end

  test do
    system "#{bin}/aitrace", "--version"
  end
end
